Twitter api
wagtail/madewithwagtail pull request #95
Opened 2017-10-13 01:09 UTC by jennyadamsnz

A few things that should/could be done that I'm not 100% sure how to do and would appreciate suggestions on:
- storing keys and tokens in a local.py? Is this needed?
- making the url in the tweet a clickable link - nice to have
- then auto-shortening the url
- setting up a character limit so that if the character limit is over 140 that the "Welcome" part of the string is dropped to give extra characters - probably good to have in case of a long website nice which will mean a long url...

2017-10-13 01:17 UTC, ryami333 reviewed
Because I haven't really worked on a Python/Django project before, I'm not certain - but my gut says that these creds shouldn't be hardcoded in here, they should be environment variables or something. Otherwise, anyone with access to this repo will be able to make tweets on behalf of that account, and they're now forever immortalised in this repo's history 😭 You may need to invalidate these keys, generate new ones, and find a way to use them without committing them.

2017-10-13 01:18 UTC, jennyadamsnz commented
I've run a test on my local to the new MWW Twitter profile (currently private) which is here and shows a test run of the current code: https://twitter.com/MadeWithWagtail

2017-10-16 00:33 UTC, loicteixeira commented
As agreed last week I'll have a look at this PR later this week, however as @ryami333 pointed, this repo is public, therefore anybody can read the credentials. 

Things to do now:
- Remove the `twitter_credentials.py` file.
- Add the required keys to `local.py.example` so people know that those keys are expected.
- Rebase the branch to remove any trace of the `twitter_credentials.py` file. It should appear that this file never existed.
- Force push the rebase branch to the remote
- Log into Twitter and make the current credentials invalid.

On deployment, we will need to make sure to update `local.py` with the required keys.

2017-10-17 20:09 UTC, jennyadamsnz commented
Cool, thanks everyone. Will do today. Fortunately I made the twitter ac private ;) whew!

2017-10-19 08:55 UTC, loicteixeira requested changes
Nice work 👌

How do you like Python? 😄 

I haven't had time to run the code so hopefully my comments aren't too out of place.

2017-10-19 08:55 UTC, loicteixeira commented on .gitignore
> +credentials.py
This shouldn't be necessary anymore.

2017-10-19 08:55 UTC, loicteixeira commented on madewithwagtail/settings/local.py.example
> +ACCESS_TOKEN_SECRET = ''
Please prefix the 4 constants with `TWITTER_` to keep things tidy.

2017-10-19 08:55 UTC, loicteixeira commented on core/signals.py
> +        url = "https://www.sp.co.nz/"
This should be `url = page.url`

2017-10-19 08:55 UTC, loicteixeira commented on core/signals.py
> +        api.update_with_media(page.image_desktop.file.name, tweet, file=page.image_desktop.file);
`WagtailSitePage.image_desktop` isn't a required field and might be `None`. I know we normally set one but the code should send a text only tweet if there is no image.

2017-10-19 08:55 UTC, loicteixeira commented on core/signals.py
> +        urlMaxSize = 23
Where does that number comes from?

2017-10-19 08:55 UTC, loicteixeira commented on madewithwagtail/settings/base.py
> +from .twitter_credentials import CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET
This shouldn't be there.

2017-10-19 08:55 UTC, loicteixeira commented on core/signals.py
> +        api.update_with_media(page.image_desktop.file.name, tweet, file=page.image_desktop.file);
Also, doesn't an image take some of the character length away?

2017-10-26 08:50 UTC, jennyadamsnz commented on .gitignore
> +credentials.py
done

2017-10-26 08:50 UTC, jennyadamsnz commented on core/signals.py
> +        url = "https://www.sp.co.nz/"
yeah thanks, leftover from testing

2017-10-26 08:53 UTC, jennyadamsnz commented on core/signals.py
> +        urlMaxSize = 23
apparently twitter truncates urls to 23 characters automatically but this is set as a back up :) https://support.twitter.com/articles/78124

2017-10-26 08:59 UTC, jennyadamsnz commented on madewithwagtail/settings/base.py
> +from .twitter_credentials import CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET
thx

2017-10-26 09:05 UTC, jennyadamsnz commented on madewithwagtail/settings/local.py.example
> +ACCESS_TOKEN_SECRET = ''
ok, will do

2017-10-26 09:50 UTC, jennyadamsnz commented on core/signals.py
> +        api.update_with_media(page.image_desktop.file.name, tweet, file=page.image_desktop.file);
Re char length, images don't count as of Sept 2016 so all good there.
Re image requirement, ok i'll check this out if I have time but I finish up tomorrow so no promises ;)

2017-10-26 09:54 UTC, jennyadamsnz commented
Thanks @loicteixeira for your reviews and @ryami333 for your help. Unfortunately I've now run out of time to do the final unit testing needed to finish this little project off. @thibaudcolas or @haydnnewport is that something I can leave with one of you please? I would love to see it finally finished!

2017-10-26 21:16 UTC, loicteixeira commented
Nice work @jennyadamsnz.

It's sad to see you leave but this project is public so you're more than welcome to continue the work on it if you want to complete it yourself (although you might need to either fork and create a new PR or ask infrastructure to give you write rights to this repo).

Otherwise don't worry, we will wrap it up and merge it :)

2023-11-10 00:44 UTC, closed without merging